### ISSUE TITLE
Undefined symbol crash HOI4

### ISSUE THREAD

**Issue by kernitus** [20PercentRendered/creamlinux#7]
Whilst running a hoi4 game launched from steam, the game crashes with the following error:

`./hoi4: symbol lookup error: ./hoi4: undefined symbol: _ZN3tbb10interface78internal20isolate_within_arenaERNS1_13delegate_baseEl`

The crash happens either immediately after starting a new game or shortly after loading an existing one.

**Comment by 20PercentRendered** [comment]
Can confirm. Had a similar issue before, need to find out if I'm exporting erroneous methods in libcreamlinux.so

**Comment by kernitus** [comment]
The symbol seems to belong to the `tbb` library but compiling the project with `-ltbb` flag to link it doesn't seem to make any difference.

**Comment by 20PercentRendered** [comment]
I don't think we even use tbb anywhere.

**Comment by 20PercentRendered** [comment]
The game works with creamlinux if I use steam-native. Need to link against steam runtime libraries most likely.

**Comment by 20PercentRendered** [comment]
The game crashes, because it was not meant to be ran inside the Steam Linux Runtime (SteamRT). The normal method of launching the game goes through the launcher, which removes any associations to SteamRT. The creamlinux start script runs hoi4 in SteamRT, which doesn't work. 
I've made a fix, and will release it soon.

**Comment by kernitus** [comment]
Can confirm this works now.
